# Generated by Django 4.2.2 on 2023-06-20 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visitors', '0004_remove_roomamenities_category_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='num_quests',
            new_name='num_guests',
        ),
    ]
