# Generated by Django 4.2.2 on 2023-06-25 08:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('visitors', '0008_alter_guestdetails_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='num_guests',
            new_name='num_adults',
        ),
        migrations.AddField(
            model_name='booking',
            name='num_kids',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Child',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.PositiveIntegerField()),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='visitors.booking')),
            ],
        ),
    ]
