# Generated by Django 4.2.1 on 2023-05-30 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_email_remove_person_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('people', models.ManyToManyField(related_name='addresses', to='polls.person')),
            ],
        ),
    ]
