# Generated by Django 4.2.1 on 2023-05-30 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='name',
            new_name='location',
        ),
    ]
