# Generated by Django 4.2.1 on 2023-06-06 09:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0006_alter_review_film'),
    ]

    operations = [
        migrations.CreateModel(
            name='Poster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='posters/')),
                ('explanation_img', models.CharField(max_length=255)),
                ('film', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='posters', to='films.film')),
            ],
        ),
    ]
