# Generated by Django 4.2.1 on 2023-06-06 20:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('films', '0007_poster'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poster',
            name='id',
        ),
        migrations.AlterField(
            model_name='poster',
            name='film',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='films.film'),
        ),
        migrations.AlterField(
            model_name='poster',
            name='image',
            field=models.ImageField(upload_to='media/posters/'),
        ),
        migrations.CreateModel(
            name='FavoriteFilm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('film', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='films.film')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_films', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'film')},
            },
        ),
    ]
