# Generated by Django 4.2.1 on 2023-06-07 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0008_remove_poster_id_alter_poster_film_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poster',
            name='image',
            field=models.ImageField(upload_to='posters/'),
        ),
    ]
